insert into roles (id, name) values(1,'USER');
insert into users (id, email, user_name, password) values(1, 'test@test.com', 'test','notmaching');
insert into users (id, email, user_name, password) values(2, 'mighty_thor@test.com', 'thor','$2a$10$vi9zwKWjnF5MktoTVOGvKeJQ/Qwz78X/ms9zHaBQ5B/ROCFisChmi');
insert into users (id, email, user_name, password) values(3, 'ironman@test.com', 'ironman','$2a$10$vi9zwKWjnF5MktoTVOGvKeJQ/Qwz78X/ms9zHaBQ5B/ROCFisChmi');
insert into user_roles (user_id, role_id) values (1, 1);
insert into user_roles (user_id, role_id) values (2, 1);
insert into user_roles (user_id, role_id) values (3, 1);

insert into tournament_type(name) values('taekwondo');

insert into tournament (id, owner_id, type, name, date_started, date_end, status) values(1, 1, 'taekwondo','PatagoniaOpen', '2024-05-15', '2024-05-16', 'OPEN');
insert into tournament (id, owner_id, type, name, date_started, date_end, status) values(2, 2, 'taekwondo','PatagoniaOpen', '2024-05-15', '2024-05-16', 'OPEN');

insert into tournament (id, owner_id, type, name, date_started, date_end, status) values(3, 1,'taekwondo', 'Patagonia Open 2023', '2023-05-15', '2023-05-16', 'CLOSED');
insert into tournament (id, owner_id, type, name, date_started, date_end, status) values(4, 1,'taekwondo', 'Patagonia Open 2022', '2022-05-15', '2022-05-16', 'CLOSED');

insert into participant_teams(id, tournament_id, name,user_subscriber_id, email) values (1, 1, 'dog masters',1, 'test@test.com');
insert into participant_teams(id, tournament_id, name,user_subscriber_id, email) values (2, 1, 'tygers', 2, 'mighty_thor@test.com');

insert into age_categories (id, tournament_id, name, min_age, max_age) values(1,1, 'adults', 30, 100);
insert into age_categories (id, tournament_id, name, min_age, max_age) values(301, 1, 'test_remove', 101, 120);

insert into age_categories (id, tournament_id, name, min_age, max_age) values(100, 4, 'infantiles', 8, 12);
insert into age_categories (id, tournament_id, name, min_age, max_age) values(101, 4, 'juveniles', 13, 17);
insert into age_categories (id, tournament_id, name, min_age, max_age) values(102, 4, 'adultos', 18, 35);
insert into age_categories (id, tournament_id, name, min_age, max_age) values(103, 4, 'seniors', 36, 120);



insert into belt_categories (id, tournament_id, name) values(1,1,'dan');

insert into base_categories (id, tournament_id, sex, type, format, num_participant, name) values(1, 1, 'MALE', 'COMBAT', 'SINGLE_ELIMINATION', 1, 'combat');
insert into combat_categories (id, age_category_id, min_weight, max_weight) values(1, 1, 80, 150);

insert into base_categories (id, tournament_id, sex, type, format) values(2, 1, 'MALE', 'FORM', 'STAGES');
insert into form_categories (id, min_age, max_age) values (2, 35, 100);

insert into accounts(id, association_name, phone_number, owner_id, country_code) values (88, 'Andina', '223456888', 1, 'ARG');
insert into accounts(id, association_name, phone_number, owner_id, country_code) values (77, 'Two Times', '4658889', 3, 'ARG');

insert into countries (name, code) values ('Afghanistan','AFG');
insert into countries (name, code) values ('Albania','ALB');
insert into countries (name, code) values ('Algeria','DZA');
insert into countries (name, code) values ('American Samoa','ASM');
insert into countries (name, code) values ('Andorra','AND');
insert into countries (name, code) values ('Angola','AGO');
insert into countries (name, code) values ('Anguilla','AIA');
insert into countries (name, code) values ('Antarctica','ATA');
insert into countries (name, code) values ('Antigua and Barbuda','ATG');
insert into countries (name, code) values ('Argentina','ARG');
insert into countries (name, code) values ('Armenia','ARM');
insert into countries (name, code) values ('Aruba','ABW');
insert into countries (name, code) values ('Australia','AUS');
insert into countries (name, code) values ('Austria','AUT');
insert into countries (name, code) values ('Azerbaijan','AZE');
insert into countries (name, code) values ('Bahamas','BHS');
insert into countries (name, code) values ('Bahrain','BHR');
insert into countries (name, code) values ('Bangladesh','BGD');
insert into countries (name, code) values ('Barbados','BRB');
insert into countries (name, code) values ('Belarus','BLR');
insert into countries (name, code) values ('Belgium','BEL');
insert into countries (name, code) values ('Belize','BLZ');
insert into countries (name, code) values ('Benin','BEN');
insert into countries (name, code) values ('Bermuda','BMU');
insert into countries (name, code) values ('Bhutan','BTN');
insert into countries (name, code) values ('Bolivia','BOL');
insert into countries (name, code) values ('Bosnia and Herzegovina','BIH');
insert into countries (name, code) values ('Botswana','BWA');
insert into countries (name, code) values ('Brazil','BRA');
insert into countries (name, code) values ('British Indian Ocean Territory','IOT');
insert into countries (name, code) values ('British Virgin Islands','VGB');
insert into countries (name, code) values ('Brunei','BRN');
insert into countries (name, code) values ('Bulgaria','BGR');
insert into countries (name, code) values ('Burkina Faso','BFA');
insert into countries (name, code) values ('Burundi','BDI');
insert into countries (name, code) values ('Cambodia','KHM');
insert into countries (name, code) values ('Cameroon','CMR');
insert into countries (name, code) values ('Canada','CAN');
insert into countries (name, code) values ('Cape Verde','CPV');
insert into countries (name, code) values ('Cayman Islands','CYM');
insert into countries (name, code) values ('Central African Republic','CAF');
insert into countries (name, code) values ('Chad','TCD');
insert into countries (name, code) values ('Chile','CHL');
insert into countries (name, code) values ('China','CHN');
insert into countries (name, code) values ('Christmas Island','CXR');
insert into countries (name, code) values ('Cocos Islands','CCK');
insert into countries (name, code) values ('Colombia','COL');
insert into countries (name, code) values ('Comoros','COM');
insert into countries (name, code) values ('Cook Islands','COK');
insert into countries (name, code) values ('Costa Rica','CRI');
insert into countries (name, code) values ('Croatia','HRV');
insert into countries (name, code) values ('Cuba','CUB');
insert into countries (name, code) values ('Curacao','CUW');
insert into countries (name, code) values ('Cyprus','CYP');
insert into countries (name, code) values ('Czech Republic','CZE');
insert into countries (name, code) values ('Democratic Republic of the Congo','COD');
insert into countries (name, code) values ('Denmark','DNK');
insert into countries (name, code) values ('Djibouti','DJI');
insert into countries (name, code) values ('Dominica','DMA');
insert into countries (name, code) values ('Dominican Republic','DOM');
insert into countries (name, code) values ('East Timor','TLS');
insert into countries (name, code) values ('Ecuador','ECU');
insert into countries (name, code) values ('Egypt','EGY');
insert into countries (name, code) values ('El Salvador','SLV');
insert into countries (name, code) values ('Equatorial Guinea','GNQ');
insert into countries (name, code) values ('Eritrea','ERI');
insert into countries (name, code) values ('Estonia','EST');
insert into countries (name, code) values ('Ethiopia','ETH');
insert into countries (name, code) values ('Falkland Islands','FLK');
insert into countries (name, code) values ('Faroe Islands','FRO');
insert into countries (name, code) values ('Fiji','FJI');
insert into countries (name, code) values ('Finland','FIN');
insert into countries (name, code) values ('France','FRA');
insert into countries (name, code) values ('French Polynesia','PYF');
insert into countries (name, code) values ('Gabon','GAB');
insert into countries (name, code) values ('Gambia','GMB');
insert into countries (name, code) values ('Georgia','GEO');
insert into countries (name, code) values ('Germany','DEU');
insert into countries (name, code) values ('Ghana','GHA');
insert into countries (name, code) values ('Gibraltar','GIB');
insert into countries (name, code) values ('Greece','GRC');
insert into countries (name, code) values ('Greenland','GRL');
insert into countries (name, code) values ('Grenada','GRD');
insert into countries (name, code) values ('Guam','GUM');
insert into countries (name, code) values ('Guatemala','GTM');
insert into countries (name, code) values ('Guernsey','GGY');
insert into countries (name, code) values ('Guinea','GIN');
insert into countries (name, code) values ('Guinea-Bissau','GNB');
insert into countries (name, code) values ('Guyana','GUY');
insert into countries (name, code) values ('Haiti','HTI');
insert into countries (name, code) values ('Honduras','HND');
insert into countries (name, code) values ('Hong Kong','HKG');
insert into countries (name, code) values ('Hungary','HUN');
insert into countries (name, code) values ('Iceland','ISL');
insert into countries (name, code) values ('India','IND');
insert into countries (name, code) values ('Indonesia','IDN');
insert into countries (name, code) values ('Iran','IRN');
insert into countries (name, code) values ('Iraq','IRQ');
insert into countries (name, code) values ('Ireland','IRL');
insert into countries (name, code) values ('Isle of Man','IMN');
insert into countries (name, code) values ('Israel','ISR');
insert into countries (name, code) values ('Italy','ITA');
insert into countries (name, code) values ('Ivory Coast','CIV');
insert into countries (name, code) values ('Jamaica','JAM');
insert into countries (name, code) values ('Japan','JPN');
insert into countries (name, code) values ('Jersey','JEY');
insert into countries (name, code) values ('Jordan','JOR');
insert into countries (name, code) values ('Kazakhstan','KAZ');
insert into countries (name, code) values ('Kenya','KEN');
insert into countries (name, code) values ('Kiribati','KIR');
insert into countries (name, code) values ('Kosovo','XKX');
insert into countries (name, code) values ('Kuwait','KWT');
insert into countries (name, code) values ('Kyrgyzstan','KGZ');
insert into countries (name, code) values ('Laos','LAO');
insert into countries (name, code) values ('Latvia','LVA');
insert into countries (name, code) values ('Lebanon','LBN');
insert into countries (name, code) values ('Lesotho','LSO');
insert into countries (name, code) values ('Liberia','LBR');
insert into countries (name, code) values ('Libya','LBY');
insert into countries (name, code) values ('Liechtenstein','LIE');
insert into countries (name, code) values ('Lithuania','LTU');
insert into countries (name, code) values ('Luxembourg','LUX');
insert into countries (name, code) values ('Macau','MAC');
insert into countries (name, code) values ('Macedonia','MKD');
insert into countries (name, code) values ('Madagascar','MDG');
insert into countries (name, code) values ('Malawi','MWI');
insert into countries (name, code) values ('Malaysia','MYS');
insert into countries (name, code) values ('Maldives','MDV');
insert into countries (name, code) values ('Mali','MLI');
insert into countries (name, code) values ('Malta','MLT');
insert into countries (name, code) values ('Marshall Islands','MHL');
insert into countries (name, code) values ('Mauritania','MRT');
insert into countries (name, code) values ('Mauritius','MUS');
insert into countries (name, code) values ('Mayotte','MYT');
insert into countries (name, code) values ('Mexico','MEX');
insert into countries (name, code) values ('Micronesia','FSM');
insert into countries (name, code) values ('Moldova','MDA');
insert into countries (name, code) values ('Monaco','MCO');
insert into countries (name, code) values ('Mongolia','MNG');
insert into countries (name, code) values ('Montenegro','MNE');
insert into countries (name, code) values ('Montserrat','MSR');
insert into countries (name, code) values ('Morocco','MAR');
insert into countries (name, code) values ('Mozambique','MOZ');
insert into countries (name, code) values ('Myanmar','MMR');
insert into countries (name, code) values ('Namibia','NAM');
insert into countries (name, code) values ('Nauru','NRU');
insert into countries (name, code) values ('Nepal','NPL');
insert into countries (name, code) values ('Netherlands','NLD');
insert into countries (name, code) values ('Netherlands Antilles','ANT');
insert into countries (name, code) values ('New Caledonia','NCL');
insert into countries (name, code) values ('New Zealand','NZL');
insert into countries (name, code) values ('Nicaragua','NIC');
insert into countries (name, code) values ('Niger','NER');
insert into countries (name, code) values ('Nigeria','NGA');
insert into countries (name, code) values ('Niue','NIU');
insert into countries (name, code) values ('North Korea','PRK');
insert into countries (name, code) values ('Northern Mariana Islands','MNP');
insert into countries (name, code) values ('Norway','NOR');
insert into countries (name, code) values ('Oman','OMN');
insert into countries (name, code) values ('Pakistan','PAK');
insert into countries (name, code) values ('Palau','PLW');
insert into countries (name, code) values ('Palestine','PSE');
insert into countries (name, code) values ('Panama','PAN');
insert into countries (name, code) values ('Papua New Guinea','PNG');
insert into countries (name, code) values ('Paraguay','PRY');
insert into countries (name, code) values ('Peru','PER');
insert into countries (name, code) values ('Philippines','PHL');
insert into countries (name, code) values ('Pitcairn','PCN');
insert into countries (name, code) values ('Poland','POL');
insert into countries (name, code) values ('Portugal','PRT');
insert into countries (name, code) values ('Puerto Rico','PRI');
insert into countries (name, code) values ('Qatar','QAT');
insert into countries (name, code) values ('Republic of the Congo','COG');
insert into countries (name, code) values ('Reunion','REU');
insert into countries (name, code) values ('Romania','ROU');
insert into countries (name, code) values ('Russia','RUS');
insert into countries (name, code) values ('Rwanda','RWA');
insert into countries (name, code) values ('Saint Barthelemy','BLM');
insert into countries (name, code) values ('Saint Helena','SHN');
insert into countries (name, code) values ('Saint Kitts and Nevis','KNA');
insert into countries (name, code) values ('Saint Lucia','LCA');
insert into countries (name, code) values ('Saint Martin','MAF');
insert into countries (name, code) values ('Saint Pierre and Miquelon','SPM');
insert into countries (name, code) values ('Saint Vincent and the Grenadines','VCT');
insert into countries (name, code) values ('Samoa','WSM');
insert into countries (name, code) values ('San Marino','SMR');
insert into countries (name, code) values ('Sao Tome and Principe','STP');
insert into countries (name, code) values ('Saudi Arabia','SAU');
insert into countries (name, code) values ('Senegal','SEN');
insert into countries (name, code) values ('Serbia','SRB');
insert into countries (name, code) values ('Seychelles','SYC');
insert into countries (name, code) values ('Sierra Leone','SLE');
insert into countries (name, code) values ('Singapore','SGP');
insert into countries (name, code) values ('Sint Maarten','SXM');
insert into countries (name, code) values ('Slovakia','SVK');
insert into countries (name, code) values ('Slovenia','SVN');
insert into countries (name, code) values ('Solomon Islands','SLB');
insert into countries (name, code) values ('Somalia','SOM');
insert into countries (name, code) values ('South Africa','ZAF');
insert into countries (name, code) values ('South Korea','KOR');
insert into countries (name, code) values ('South Sudan','SSD');
insert into countries (name, code) values ('Spain','ESP');
insert into countries (name, code) values ('Sri Lanka','LKA');
insert into countries (name, code) values ('Sudan','SDN');
insert into countries (name, code) values ('Suriname','SUR');
insert into countries (name, code) values ('Svalbard and Jan Mayen','SJM');
insert into countries (name, code) values ('Swaziland','SWZ');
insert into countries (name, code) values ('Sweden','SWE');
insert into countries (name, code) values ('Switzerland','CHE');
insert into countries (name, code) values ('Syria','SYR');
insert into countries (name, code) values ('Taiwan','TWN');
insert into countries (name, code) values ('Tajikistan','TJK');
insert into countries (name, code) values ('Tanzania','TZA');
insert into countries (name, code) values ('Thailand','THA');
insert into countries (name, code) values ('Togo','TGO');
insert into countries (name, code) values ('Tokelau','TKL');
insert into countries (name, code) values ('Tonga','TON');
insert into countries (name, code) values ('Trinidad and Tobago','TTO');
insert into countries (name, code) values ('Tunisia','TUN');
insert into countries (name, code) values ('Turkey','TUR');
insert into countries (name, code) values ('Turkmenistan','TKM');
insert into countries (name, code) values ('Turks and Caicos Islands','TCA');
insert into countries (name, code) values ('Tuvalu','TUV');
insert into countries (name, code) values ('U.S. Virgin Islands','VIR');
insert into countries (name, code) values ('Uganda','UGA');
insert into countries (name, code) values ('Ukraine','UKR');
insert into countries (name, code) values ('United Arab Emirates','ARE');
insert into countries (name, code) values ('United Kingdom','GBR');
insert into countries (name, code) values ('United States','USA');
insert into countries (name, code) values ('Uruguay','URY');
insert into countries (name, code) values ('Uzbekistan','UZB');
insert into countries (name, code) values ('Vanuatu','VUT');
insert into countries (name, code) values ('Vatican','VAT');
insert into countries (name, code) values ('Venezuela','VEN');
insert into countries (name, code) values ('Vietnam','VNM');
insert into countries (name, code) values ('Wallis and Futuna','WLF');
insert into countries (name, code) values ('Western Sahara','ESH');
insert into countries (name, code) values ('Yemen','YEM');
insert into countries (name, code) values ('Zambia','ZMB');
insert into countries (name, code) values ('Zimbabwe','ZWE');